application: play-info
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: main.html
  upload: main.html

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /api/.*
  script: api.api
